# Generated by Django 4.0.2 on 2022-04-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0003_rename_women_womens_of_kazakhstan_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='womens_of_kazakhstan',
            name='cat',
        ),
        migrations.AddField(
            model_name='womens_of_kazakhstan',
            name='slug',
            field=models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
