# Generated by Django 4.0.2 on 2022-04-13 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0004_remove_womens_of_kazakhstan_cat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dateBorn', models.DateField(unique=True)),
                ('phonenumber', models.IntegerField()),
                ('password', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Register',
            },
        ),
    ]
