# Generated by Django 4.0.2 on 2022-04-13 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0005_registermodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegisterModel',
        ),
    ]
