# Generated by Django 4.0.2 on 2022-04-13 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0006_delete_registermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.IntegerField(default='+7 ', unique=True)),
                ('password', models.CharField(max_length=16)),
                ('password_again', models.CharField(max_length=16)),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
        ),
    ]
