# Generated by Django 4.0.2 on 2022-04-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0007_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_name',
        ),
    ]
