# Generated by Django 4.0.2 on 2022-04-14 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0012_alter_user_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
