# Generated by Django 4.0.4 on 2022-05-06 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0018_alter_order_order_alter_order_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order',
            field=models.TextField(unique=True),
        ),
    ]
