# Generated by Django 4.0.4 on 2022-05-06 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0020_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_Status',
        ),
    ]
