# Generated by Django 4.0.4 on 2022-05-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0022_user_alter_order_order_alter_order_order_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='cities',
            name='img',
            field=models.ImageField(default=None, upload_to=None),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
