# Generated by Django 4.0.4 on 2022-05-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0023_remove_order_customer_cities_img_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='img',
        ),
    ]
