# Generated by Django 4.0.4 on 2022-05-08 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0025_remove_food_images_cities_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='images',
            field=models.ImageField(blank=True, max_length=200, upload_to='static/'),
        ),
        migrations.AddField(
            model_name='university',
            name='images',
            field=models.ImageField(blank=True, max_length=200, upload_to='static/'),
        ),
    ]
