# Generated by Django 4.0.4 on 2022-05-08 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0026_food_images_university_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='images',
        ),
        migrations.AddField(
            model_name='university',
            name='link',
            field=models.CharField(default=True, max_length=255),
        ),
    ]
