# Generated by Django 4.0.4 on 2022-05-09 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0027_remove_university_images_university_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='images',
        ),
        migrations.AddField(
            model_name='cities',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='img/%y'),
        ),
    ]
