# Generated by Django 4.0.4 on 2022-05-09 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0028_remove_cities_images_cities_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='img/%y'),
        ),
    ]
