# Generated by Django 4.0.4 on 2022-05-12 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0034_order_name_alter_feedback_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(default='Sultan', max_length=100),
        ),
    ]
