# Generated by Django 4.0.4 on 2022-05-12 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0035_alter_order_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='name',
        ),
    ]
