# Generated by Django 4.0.4 on 2022-05-12 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0037_order_client_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
