# Generated by Django 4.0.4 on 2022-05-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0039_alter_cities_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cities',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/kz_app/img/'),
        ),
    ]
