# Generated by Django 4.0.4 on 2022-05-22 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0044_cities_city_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='South',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kz_app.cities', verbose_name='Data')),
            ],
        ),
    ]
