# Generated by Django 4.0.4 on 2022-05-22 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0045_south'),
    ]

    operations = [
        migrations.AddField(
            model_name='south',
            name='id_num',
            field=models.IntegerField(default=1),
        ),
    ]
