# Generated by Django 4.0.4 on 2022-05-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0047_remove_south_id_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='South',
        ),
    ]
