# Generated by Django 4.0.4 on 2022-05-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0052_alter_university_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cities',
            name='slug',
            field=models.SlugField(default=True, max_length=100, null=True, unique=True, verbose_name='URL'),
        ),
    ]
