# Generated by Django 4.0.4 on 2022-05-22 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0056_alter_cities_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='slug',
        ),
    ]
