# Generated by Django 4.0.4 on 2022-05-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0060_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='slug',
        ),
    ]
