# Generated by Django 4.0.4 on 2022-05-22 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0065_alter_cities_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cities',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='university',
            name='location',
        ),
        migrations.AddField(
            model_name='cities',
            name='city_slug',
            field=models.SlugField(default=True, max_length=100, verbose_name='URL'),
        ),
    ]
