# Generated by Django 4.0.4 on 2022-05-22 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0068_remove_cities_city_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
        migrations.DeleteModel(
            name='University',
        ),
    ]
