# Generated by Django 4.0.4 on 2022-05-22 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0069_delete_cities_delete_university'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='img/%y')),
                ('city_id', models.IntegerField(default=1)),
                ('city_slug', models.SlugField(max_length=100, null=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
