# Generated by Django 4.0.4 on 2022-05-22 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0070_cities'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
