# Generated by Django 4.0.4 on 2022-05-22 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0071_delete_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_of_Kazakhstan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
                ('city_description', models.TextField()),
                ('city_id', models.IntegerField()),
                ('city_slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': 'Cities_of_Kazakhstan',
            },
        ),
    ]
