# Generated by Django 4.0.4 on 2022-05-22 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0072_city_of_kazakhstan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_of_kazakhstan',
            name='city_slug',
            field=models.SlugField(max_length=100, verbose_name='URL'),
        ),
    ]
