# Generated by Django 4.0.4 on 2022-05-22 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0073_alter_city_of_kazakhstan_city_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city_of_kazakhstan',
            name='city_slug',
        ),
    ]
