# Generated by Django 4.0.4 on 2022-05-22 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0074_remove_city_of_kazakhstan_city_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City_of_Kazakhstan',
        ),
    ]
