# Generated by Django 4.0.4 on 2022-05-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kz_app', '0075_delete_city_of_kazakhstan'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=True, max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='static/kz_app/img')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
    ]
